---
- name: Install Grafana
  hosts: localhost
  connection: local
  become: yes
  vars:
    listen_address: 0.0.0.0
    listen_port: 9090

  tasks:
  - name: Download apt key
    ansible.builtin.apt_key:
      url: https://packages.grafana.com/gpg.key
      state: present

  - name: Add Grafana to sources.list
    ansible.builtin.apt_repository:
     repo: deb https://packages.grafana.com/oss/deb stable main
     filename: grafana
     state: present

  - name: Update the apt cache and install Grafana
    ansible.builtin.apt:
     name: grafana
     update_cache: yes

  - name: Ensure Grafana is started and enabled
    ansible.builtin.systemd:
      name: grafana-server
      enabled: true
      state: started

  - name: Download Prometheus
    ansible.builtin.get_url:
      url: https://github.com/prometheus/prometheus/releases/download/v2.30.3/prometheus-2.30.3.linux-amd64.tar.gz
      dest: /home/ubuntu

  - name: Extract prom resources
    ansible.builtin.unarchive:
      src: /home/ubuntu/prometheus-2.30.3.linux-amd64.tar.gz
      dest: /home/ubuntu
      remote_src: yes

  - name: Create Prom Group
    ansible.builtin.group:
      name: prometheus
      state: present

  - name: Create Prom User
    ansible.builtin.user:
      name: prometheus
      group: prometheus
      shell: /sbin/nologin

  - name: Create prom directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      recurse: true
      owner: prometheus
      group: prometheus
      mode: "0755"
    loop:
      - /etc/prometheus
      - /etc/prometheus/rules
      - /etc/prometheus/rules.d
      - /etc/prometheus/files_sd
      - /var/lib/prometheus

  - name: Copy files
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /usr/local/bin
      remote_src: yes
      mode: "0755"
      owner: prometheus
      group: prometheus
    loop:
      - /home/ubuntu/prometheus-2.30.3.linux-amd64/prometheus
      - /home/ubuntu/prometheus-2.30.3.linux-amd64/promtool

  - name: Copy Files
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /etc/prometheus
      remote_src: yes
    loop:
      - /home/ubuntu/prometheus-2.30.3.linux-amd64/consoles/
      - /home/ubuntu/prometheus-2.30.3.linux-amd64/console_libraries

  - name: Create config file
    ansible.builtin.template:
      src: /home/ubuntu/terraform-ansible-workflow/ansible/templates/prometheus.yml.j2
      dest: /etc/prometheus/prometheus.yml

  - name:
    ansible.builtin.template: 
      src:  /home/ubuntu/terraform-ansible-workflow/ansible/templates/prometheus.service.j2
      dest: /etc/systemd/system/prometheus.service

  - name: Ensure prom is started
    ansible.builtin.systemd:
      name: prometheus
      state: started
      enabled: yes

  - name: ensure the jenkins apt repository key is installed
    ansible.builtin.apt_key: 
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key 
      state: present

  - name: ensure the repository is configured
    ansible.builtin.apt_repository: 
      repo: 'deb https://pkg.jenkins.io/debian-stable binary/' 
      state: present

  - name: ensure jenkins is installed
    ansible.builtin.apt: 
      name: jenkins 
      update_cache: yes

  - name: ensure jenkins is running
    ansible.builtin.systemd: 
      name: jenkins 
      state: started


  - name: Import docker and docker compose playbook
    ansible.builtin.import_tasks:
      file: /home/ubuntu/terraform-ansible-workflow/ansible/playbooks/docker.yml

